<a href="https://colab.research.google.com/github/chiinmayy/Machine_Learning_7072CEM/blob/main/Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv("/content/dataset.csv")
X : pd.DataFrame = df[['Portugese','Kolkata','Mumbai','Qatar','Delhi','America']]
Y : pd.DataFrame = df['class']


In [3]:
type(X)

pandas.core.frame.DataFrame

In [4]:
import numpy as np
X = X.to_numpy()
Y = Y.to_numpy()

In [5]:
print(X)

[[2 1 0 0 0 0]
 [2 0 1 0 0 0]
 [1 0 0 1 0 0]
 [1 0 0 0 1 1]]


Training NB Classsifier

In [6]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf = clf.fit(X, Y)

In [7]:
test = [3, 0, 0, 0, 1, 1]

Prediction

In [8]:
pred = clf.predict([test])

print(pred)

[1]
